apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j49hwhfdh-nodejs
  janus-idp.io/tekton: j49hwhfdh-nodejs
  backstage.io/kubernetes-id: j49hwhfdh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j49hwhfdh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
